services:
  db:
    image: postgres:16-alpine
    container_name: auto_parking_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auto-parking:
    build: .
    container_name: auto_parking_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}
      TEST_ADMIN_LOGIN: ${TEST_ADMIN_LOGIN}
      TEST_ADMIN_PASS: ${TEST_ADMIN_PASS}
    command: uvicorn auto_parking.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    container_name: auto_parking_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - auto-parking

volumes:
  db_data: