global:
  scrape_interval: 5s

scrape_configs:
  - job_name: auto-parking-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - auto-parking:8000

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
