"""create managers

Revision ID: 691fd6282453
Revises: f9b11a481598
Create Date: 2026-02-16 14:56:44.969314

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "691fd6282453"
down_revision = "f9b11a481598"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manager",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name=op.f("uq_manager_username")),
    )
    op.create_index(op.f("ix_manager_username"), "manager", ["username"], unique=True)
    op.create_table(
        "manager_enterprise",
        sa.Column("manager_id", sa.BigInteger(), nullable=False),
        sa.Column("enterprise_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["manager_id"], ["manager.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manager_id", "enterprise_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manager_enterprise")
    op.drop_constraint(op.f("uq_manager_username"), "manager", type_="unique")
    op.drop_index(op.f("ix_manager_username"), table_name="manager")
    op.drop_table("manager")
    # ### end Alembic commands ###
