"""create vehicle

Revision ID: 76538932edae
Revises:
Create Date: 2026-01-30 14:30:33.952261

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "76538932edae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("mileage", sa.BigInteger(), nullable=False),
        sa.Column("vehicle_number", sa.String(), nullable=False, unique=True),
        sa.Column("owners_count", sa.Integer(), nullable=False),
        sa.Column("accident_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("manufacture_year", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle")
    # ### end Alembic commands ###
