"""create vehicle model

Revision ID: cdbec0af3d5a
Revises: 76538932edae
Create Date: 2026-02-01 09:09:49.655494

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cdbec0af3d5a"
down_revision = "76538932edae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_model",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("horse_powers", sa.Integer(), nullable=False),
        sa.Column("seats_number", sa.Integer(), nullable=False),
        sa.Column("fuel_capacity_liters", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("vehicle", sa.Column("model_id", sa.BigInteger(), nullable=False))
    op.create_index(op.f("ix_vehicle_model_id"), "vehicle", ["model_id"], unique=False)
    op.create_foreign_key("fkey_model", "vehicle", "vehicle_model", ["model_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fkey_model", "vehicle", type_="foreignkey")
    op.drop_index(op.f("ix_vehicle_model_id"), table_name="vehicle")
    op.drop_column("vehicle", "model_id")
    op.drop_table("vehicle_model")
    # ### end Alembic commands ###
