"""create drivers and enterprises

Revision ID: f9b11a481598
Revises: cdbec0af3d5a
Create Date: 2026-02-03 16:39:19.624041

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f9b11a481598"
down_revision = "cdbec0af3d5a"
branch_labels = None
depends_on = None


def upgrade():
    # Создание Enterprises
    op.create_table(
        "enterprise",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("settlement", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    conn = op.get_bind()
    unknown_id = conn.execute(
        sa.text("""
                            INSERT INTO enterprise (name, settlement, created_at)
                            VALUES (:name, :settlement, now())
                            RETURNING id
                        """),
        {"name": "неизвестно", "settlement": "неизвестно"},
    ).scalar_one()
    # >---------------------------<
    # Добавление колонки со ссылкой на Enterprises и превращение ее в not nullable + индекс
    op.add_column("vehicle", sa.Column("enterprise_id", sa.BigInteger(), nullable=True))
    conn.execute(
        sa.text("""
            UPDATE vehicle v
            SET enterprise_id = :eid
            WHERE v.enterprise_id IS NULL
               OR NOT EXISTS (
                    SELECT 1 FROM enterprise e WHERE e.id = v.enterprise_id
               );
        """),
        {"eid": unknown_id},
    )
    op.alter_column("vehicle", "enterprise_id", nullable=False)
    op.create_foreign_key(
        "fk_vehicle_enterprise_id",
        "vehicle",
        "enterprise",
        ["enterprise_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(op.f("ix_vehicle_enterprise_id"), "vehicle", ["enterprise_id"], unique=False)

    # Создание таблицы водителей
    op.create_table(
        "driver",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("salary_rub", sa.BigInteger(), nullable=False),
        sa.Column("enterprise_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Добавление ссылки на активного водителя в Vehicles
    op.add_column("vehicle", sa.Column("active_driver_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "fk_vehicle_active_driver_id",
        "vehicle",
        "driver",
        ["active_driver_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_unique_constraint(
        "uq_vehicle_active_driver_id",
        "vehicle",
        ["active_driver_id"],
    )

    # N-N таблица для водителей и машин
    op.create_table(
        "vehicle_driver_assignment",
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id", "driver_id"),
    )

    # минорные изменения в уже существующих таблицах
    op.alter_column("vehicle", "manufacture_year", existing_type=sa.SMALLINT(), nullable=True)
    op.alter_column("vehicle_model", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("vehicle_model", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("vehicle_model", "horse_powers", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("vehicle_model", "seats_number", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "vehicle_model", "fuel_capacity_liters", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicle_model", "fuel_capacity_liters", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("vehicle_model", "seats_number", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("vehicle_model", "horse_powers", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("vehicle_model", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("vehicle_model", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint("fk_vehicle_enterprise_id", "vehicle", type_="foreignkey")
    op.drop_index(op.f("ix_vehicle_enterprise_id"), table_name="vehicle")
    op.drop_constraint("uq_vehicle_active_driver_id", "vehicle", type_="unique")
    op.drop_constraint("fk_vehicle_active_driver_id", "vehicle", type_="foreignkey")
    op.drop_column("vehicle", "active_driver_id")
    op.alter_column("vehicle", "manufacture_year", existing_type=sa.SMALLINT(), nullable=False)
    op.drop_column("vehicle", "enterprise_id")
    op.drop_table("vehicle_driver_assignment")
    op.drop_table("driver")
    op.drop_table("enterprise")
    # ### end Alembic commands ###
